config/routes.rb
SecondProject::Application.routes.draw do
    root  'static_pages#home'
    match '/faq',    to: 'static_pages#faq',    via: 'get'
    match '/about',   to: 'static_pages#about',   via: 'get'
    match '/blog',    to: 'static_pages#blog', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def faq
  end

  def about
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_title(page_title)
      base_title = "This is our Second Project"
      if page_title.empty?
        base_title
      else
        "#{base_title}| #{page_title}"
      end
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://wall.alphacoders.com/by_sub_category.php?id=179743">Dragon Ball Tutorial</a>
    by Yihong dai, di zhen
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Second Project", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Faq",    faq_path %></li>
          <li><%= link_to "Blog", blog_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
	  <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>


<h1>This is About Us on Dragon Ball</h1>
<p>
  The <a href="http://dragonball.wikia.com/wiki/Main_Page">This is Dragon Ball Tutorial</a>
  is a project to familiarize you with the classic dragon ball anime <a href="http://www.youtube.com/watch?v=1GYYV5a5B_o">DB opening</a>. This
  is the About us for the tutorial.
</p>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog')%>

<h1>Here we share Dragon ball Blog </h1>
<p>
  The <a href="http://thedragonballblog.blogspot.com">Blog page </a>
  is the place you share your blogs
   <a href="https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fwww.blogger.com%2Fnavbar-more.g%3Fdata%3DAPq4FmBegb2FHgvKqJlWRjiTeOnu0gftf73BeUU7YQUmELQ1YqfK74WXGB1Kd_sQntHKm2h_-T8eeYk4ODPCxuKnkeG9hPmvf6oRhfwPJNeNLA0IYRVKBXhzjRXFK-kx21HgWq6QZUmbAH1226GMLhkZcMV4-WgG18ods9xgiwGfnncFmbPzMT06eLNuUCFj45_cMvBk_tMkai_RbfpYcd1eOUe9O8m8U0BjCqC-UNWCFaFoSYdWCzNcQbC1VIJchXKQBZhd2fO1%26usegapi%3D1%26jsh%3Dm%253B%252F_%252Fscs%252Fapps-static%252F_%252Fjs%252Fk%253Doz.gapi.en_US.68HYMjN3xUA.O%252Fm%253D__features__%252Fam%253DIQ%252Frt%253Dj%252Fd%253D1%252Ft%253Dzcms%252Frs%253DAItRSTMc4OEVZiUO_olTLSn-8hOqNvBIoA&text=Dragon+Blog&url=http%3A%2F%2Fthedragonballblog.blogspot.com%2F%3Fspref%3Dtw"> Share blogs on Twitter</a>. This
  is the Second Project for the tutorial.
</p>

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>

<h1>FAQ Page for Dragon ball fans</h1>
<p>
  The <a href="http://www.imdb.com/title/tt0214341/faq">Frequently asked Question</a>
  is a way to know your answers <a href="http://www.dragonballgt.com">Dragon Ball </a>. This
  is the Second Project for the tutorial.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Second Project on Dragon Ball Tutorial</h1>
<h2>
  This is the place where we enjoy Dragon Ball.
<h2>
	<a href="http://scratch.mit.edu/studios/200264/">Dragon Ball Fan Club</a>

</div>